### ISSUE TITLE
Don't use any more inline script and css

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1631]
### What is the bug?

Using inline JS and CSS content into HTML is not a good practice, as it force to set CSP header with insecure parameters. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

### Expected behavior

In templates, we should not use anymore `<script>....</script>` and `<style>...</style>`.

Static content should be stored into JS/CSS files. All code into `style=""` and `on<event>=""` should be set into CSS/JS files (for js, we should use `addEventListener()` etc.

For generated JS/CSS content depending on some parameters, we should create actions in controllers, and use their corresponding urls in `<link>` and `<script src=..`

### Todo list

- [ ] move static JS content into JS files
- [ ] move static CSS content into CSS files
- [ ] move `style=""` into CSS files
- [ ] move js code from HTML attributes (like `onclick`)  to JS files
- [ ] create controllers action for generated JS/CSS content
- [ ] use external resources by using `https://` instead of `http://` (if existing)
- [ ] upgrade some libraries that are still using `eval()`
